### ISSUE TITLE
sedra.lookup returns empty string

### ISSUE THREAD

**Issue by eli8levit** [hebcal/hebcal-swift#1]
Hi, I do following code and for currency week it returns empty string although it worked before:

```
let sedra = Sedra(year: HDate(date: Date(), calendar: .current), il: false)
return sedra.lookup(hdate: HDate(date: Date(), calendar: .current), lang: TranslationLang.en) ?? ""
```

Help will be very appreciated, thanks

**Comment by eli8levit** [comment]
I understood that the reason that result is empty **because this week is special parasha "Rosh haShana" on Shabbat**. Is the any practice to handle this cases and to display holiday parasha using the library?

**Comment by mjradwin** [comment]
You can take a look at the function `getHolidayNameForParsha` in https://github.com/mjradwin/hebcal-apple-watch/blob/main/HebcalHDate%20WatchKit%20Extension/ModelData.swift

**Comment by eli8levit** [comment]
@mjradwin thanks 🙏🏻

**Comment by eli8levit** [comment]
`getHolidayNameForParsha` is what I needed
